# Generated by Django 2.2.10 on 2020-05-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200416_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Num',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='like_comment',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='sump',
        ),
    ]
